import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/providers/theme-provider";
import { Navbar } from "./components/navigation/bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
